#include "K2Node_ReplicSetEnum.h"

#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "Misc\DefaultValueHelper.h"
#include "EdGraph/EdGraphPin.h"
#include "EdGraphSchema_K2.h"
#include "Engine/Blueprint.h"
#include "K2Node_CallFunction.h"
#include "KismetCompiler.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "ReplicK2NodeUtils.h"
#include "ReplicLibrary.h"
#include "ReplicPinOptionResolver.h"

#define LOCTEXT_NAMESPACE "ReplicSetEnumNode"

namespace
{
	const FName ExecPinName(TEXT("Execute"));
	const FName ThenPinName(TEXT("Then"));
	const FName ContextObjectPinName(TEXT("ContextObject"));
	const FName TargetObjectPinName(TEXT("TargetObject"));
	const FName PropertyNamePinName(TEXT("PropertyName"));
	const FName ValuePinName(TEXT("Value"));
	const FName SuccessPinName(TEXT("Success"));

	bool IsEnumLikeProperty(const FProperty* Property)
	{
		if (CastField<FEnumProperty>(Property))
		{
			return true;
		}

		if (const FByteProperty* ByteProperty = CastField<FByteProperty>(Property))
		{
			return ByteProperty->Enum != nullptr;
		}

		return false;
	}

	UEnum* ResolveEnumFromProperty(const FProperty* Property)
	{
		if (const FEnumProperty* EnumProperty = CastField<FEnumProperty>(Property))
		{
			return EnumProperty->GetEnum();
		}

		if (const FByteProperty* ByteProperty = CastField<FByteProperty>(Property))
		{
			return ByteProperty->Enum;
		}

		return nullptr;
	}

	bool EnumContainsValueName(const UEnum* Enum, FName ValueName)
	{
		if (!Enum || ValueName.IsNone())
		{
			return false;
		}

		return Enum->GetIndexByName(ValueName) != INDEX_NONE
			|| Enum->GetIndexByNameString(ValueName.ToString()) != INDEX_NONE;
	}

	FName GetFirstUsableEnumValueName(const UEnum* Enum)
	{
		if (!Enum)
		{
			return NAME_None;
		}

		for (int32 Index = 0; Index < Enum->NumEnums(); ++Index)
		{
			if (Enum->HasMetaData(TEXT("Hidden"), Index))
			{
				continue;
			}

			const FString NameString = Enum->GetNameStringByIndex(Index);
			if (NameString.EndsWith(TEXT("_MAX")))
			{
				continue;
			}

			return FName(*NameString);
		}

		return NAME_None;
	}

	FName ResolveEnumValueFromPin(const UEdGraphPin* ValuePin, const UEnum* Enum)
	{
		if (!ValuePin || !Enum)
		{
			return NAME_None;
		}

		const auto TryResolve = [Enum](const FString& RawValue) -> FName
		{
			if (RawValue.IsEmpty())
			{
				return NAME_None;
			}

			const FName Candidate(*RawValue);
			if (EnumContainsValueName(Enum, Candidate))
			{
				return Candidate;
			}

			int64 NumericValue = 0;
			if (FDefaultValueHelper::ParseInt64(RawValue, NumericValue))
			{
				const FString NameString = Enum->GetNameStringByValue(NumericValue);
				return NameString.IsEmpty() ? NAME_None : FName(*NameString);
			}

			return NAME_None;
		};

		if (const FName DefaultCandidate = TryResolve(ValuePin->DefaultValue); !DefaultCandidate.IsNone())
		{
			return DefaultCandidate;
		}

		if (const FName AutoCandidate = TryResolve(ValuePin->AutogeneratedDefaultValue); !AutoCandidate.IsNone())
		{
			return AutoCandidate;
		}

		return NAME_None;
	}

	bool UsesSelfAsContext(const UEdGraphPin* ContextPin)
	{
		return ContextPin && ContextPin->LinkedTo.Num() == 0 && ContextPin->DefaultObject == nullptr && ContextPin->DefaultValue.IsEmpty();
	}

	void MovePinLinksOrCopyDefaults(FKismetCompilerContext& CompilerContext, UEdGraphPin* SourcePin, UEdGraphPin* TargetPin, bool bPreserveTargetDefaultsWhenSourceUnset = false)
	{
		if (!SourcePin || !TargetPin)
		{
			return;
		}

		if (SourcePin->LinkedTo.Num() > 0)
		{
			CompilerContext.MovePinLinksToIntermediate(*SourcePin, *TargetPin);
			return;
		}

		const bool bSourceHasExplicitDefault =
			!SourcePin->DefaultValue.IsEmpty()
			|| !SourcePin->AutogeneratedDefaultValue.IsEmpty()
			|| SourcePin->DefaultObject != nullptr
			|| !SourcePin->DefaultTextValue.IsEmpty();
		if (!bSourceHasExplicitDefault && bPreserveTargetDefaultsWhenSourceUnset)
		{
			return;
		}

		TargetPin->DefaultValue = SourcePin->DefaultValue;
		TargetPin->AutogeneratedDefaultValue = SourcePin->AutogeneratedDefaultValue;
		TargetPin->DefaultObject = SourcePin->DefaultObject;
		TargetPin->DefaultTextValue = SourcePin->DefaultTextValue;
	}
}

FName UK2Node_ReplicSetEnum::GetExecPinName() { return ExecPinName; }
FName UK2Node_ReplicSetEnum::GetThenPinName() { return ThenPinName; }
FName UK2Node_ReplicSetEnum::GetContextObjectPinName() { return ContextObjectPinName; }
FName UK2Node_ReplicSetEnum::GetTargetObjectPinName() { return TargetObjectPinName; }
FName UK2Node_ReplicSetEnum::GetPropertyNamePinName() { return PropertyNamePinName; }
FName UK2Node_ReplicSetEnum::GetValuePinName() { return ValuePinName; }
FName UK2Node_ReplicSetEnum::GetSuccessPinName() { return SuccessPinName; }

UEdGraphPin* UK2Node_ReplicSetEnum::GetExecPin() const { return FindPinChecked(ExecPinName); }
UEdGraphPin* UK2Node_ReplicSetEnum::GetThenPin() const { return FindPinChecked(ThenPinName); }
UEdGraphPin* UK2Node_ReplicSetEnum::GetContextObjectPin() const { return FindPinChecked(ContextObjectPinName); }
UEdGraphPin* UK2Node_ReplicSetEnum::GetTargetObjectPin() const { return FindPinChecked(TargetObjectPinName); }
UEdGraphPin* UK2Node_ReplicSetEnum::GetPropertyNamePin() const { return FindPinChecked(PropertyNamePinName); }
UEdGraphPin* UK2Node_ReplicSetEnum::GetValuePin() const { return FindPinChecked(ValuePinName); }
UEdGraphPin* UK2Node_ReplicSetEnum::GetSuccessPin() const { return FindPinChecked(SuccessPinName); }

void UK2Node_ReplicSetEnum::HandleReplicSelectionChanged(FName ChangedPinName)
{
	if (ChangedPinName != PropertyNamePinName || bIsRefreshingPins)
	{
		return;
	}

	ReconstructNode();
	if (UEdGraph* Graph = GetGraph())
	{
		Graph->NotifyNodeChanged(this);
	}
}

void UK2Node_ReplicSetEnum::HandleEnumValueSelectionChanged(FName NewEnumValue)
{
	Modify();
	bHasPersistedEnumSelection = true;
	PersistedEnumValue = NewEnumValue;

	if (UBlueprint* Blueprint = GetBlueprint())
	{
		FBlueprintEditorUtils::MarkBlueprintAsModified(Blueprint);
	}

	if (UEdGraph* Graph = GetGraph())
	{
		Graph->NotifyNodeChanged(this);
	}
}

void UK2Node_ReplicSetEnum::AllocateDefaultPins()
{
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Exec, ExecPinName);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, ThenPinName);

	UEdGraphPin* ContextPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UObject::StaticClass(), ContextObjectPinName);
	ContextPin->bAdvancedView = true;
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UObject::StaticClass(), TargetObjectPinName);
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Name, PropertyNamePinName);
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Byte, ValuePinName);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Boolean, SuccessPinName);

	RefreshValuePinType();
	Super::AllocateDefaultPins();
}

void UK2Node_ReplicSetEnum::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);

	const FProperty* SelectedProperty = ResolveSelectedEnumProperty();
	if (!SelectedProperty)
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("MissingReplicEnumProperty", "Replic: No valid Replic enum property is selected for @@").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	UK2Node_CallFunction* CallNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	CallNode->SetFromFunction(UReplicLibrary::StaticClass()->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UReplicLibrary, SetMarkedEnum)));
	CallNode->AllocateDefaultPins();

	CompilerContext.MovePinLinksToIntermediate(*GetExecPin(), *CallNode->GetExecPin());
	CompilerContext.MovePinLinksToIntermediate(*GetThenPin(), *CallNode->GetThenPin());
	MovePinLinksOrCopyDefaults(CompilerContext, GetContextObjectPin(), CallNode->FindPinChecked(ContextObjectPinName), true);
	MovePinLinksOrCopyDefaults(CompilerContext, GetTargetObjectPin(), CallNode->FindPinChecked(TargetObjectPinName));
	MovePinLinksOrCopyDefaults(CompilerContext, GetPropertyNamePin(), CallNode->FindPinChecked(PropertyNamePinName));

	UEdGraphPin* IntermediateValuePin = CallNode->FindPinChecked(ValuePinName);
	IntermediateValuePin->PinType = GetValuePin()->PinType;
	MovePinLinksOrCopyDefaults(CompilerContext, GetValuePin(), IntermediateValuePin);

	CompilerContext.MovePinLinksToIntermediate(*GetSuccessPin(), *CallNode->GetReturnValuePin());
	BreakAllNodeLinks();
}

void UK2Node_ReplicSetEnum::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);
	if (Pin && Pin->PinName == PropertyNamePinName)
	{
		ReconstructNode();
		if (UEdGraph* Graph = GetGraph())
		{
			Graph->NotifyNodeChanged(this);
		}
	}
}

void UK2Node_ReplicSetEnum::PinConnectionListChanged(UEdGraphPin* Pin)
{
	Super::PinConnectionListChanged(Pin);
	if (Pin && Pin->PinName == TargetObjectPinName)
	{
		ReconstructNode();
		if (UEdGraph* Graph = GetGraph())
		{
			Graph->NotifyNodeChanged(this);
		}
	}
}

FText UK2Node_ReplicSetEnum::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	const FText ResolvedName = GetResolvedDisplayName();
	return ResolvedName.IsEmpty()
		? LOCTEXT("ReplicSetEnumTitle", "Replic Set Enum")
		: FText::Format(LOCTEXT("ReplicSetEnumSelectedTitle", "Replic Set {0}"), ResolvedName);
}

FText UK2Node_ReplicSetEnum::GetTooltipText() const
{
	return LOCTEXT("ReplicSetEnumTooltip", "Writes a Replic-marked enum property with a real enum pin.\n\nSelect the property first, then this node exposes the correct enum type.");
}

FText UK2Node_ReplicSetEnum::GetMenuCategory() const
{
	return LOCTEXT("ReplicCategory", "Replic");
}

void UK2Node_ReplicSetEnum::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	UClass* ActionKey = GetClass();
	if (!ActionRegistrar.IsOpenForRegistration(ActionKey))
	{
		return;
	}

	UBlueprintNodeSpawner* Spawner = UBlueprintNodeSpawner::Create(GetClass());
	check(Spawner);
	ActionRegistrar.AddBlueprintAction(ActionKey, Spawner);
}

void UK2Node_ReplicSetEnum::EarlyValidation(FCompilerResultsLog& MessageLog) const
{
	Super::EarlyValidation(MessageLog);

	const UEdGraphPin* PropertyPin = GetPropertyNamePin();
	const FName SelectedPropertyName(*PropertyPin->GetDefaultAsString());
	if (SelectedPropertyName.IsNone())
	{
		MessageLog.Error(TEXT("Replic: No enum property is selected for @@"), this);
		return;
	}

	const FProperty* SelectedProperty = ResolveSelectedEnumProperty();
	if (!SelectedProperty)
	{
		UClass* TargetClass = nullptr;
		if (!ReplicPinOptionResolver::ResolveTargetClass(PropertyPin, TargetClass))
		{
			MessageLog.Warning(TEXT("Replic: TargetObject could not be resolved to a concrete class for @@"), this);
			return;
		}

		MessageLog.Error(
			*FString::Printf(TEXT("Replic: '%s' is not a Replic-marked enum property on target class '%s' for @@"), *SelectedPropertyName.ToString(), *TargetClass->GetName()),
			this);
		return;
	}

	if (!ReplicK2NodeUtils::ArePinAndPropertyCompatible(GetValuePin(), SelectedProperty))
	{
		MessageLog.Error(TEXT("Replic: Value pin does not match the selected enum property for @@"), this);
	}

	if (const UBlueprint* Blueprint = GetBlueprint())
	{
		if (UsesSelfAsContext(GetContextObjectPin()) && !ReplicK2NodeUtils::HasReplicTransportComponent(Blueprint))
		{
			MessageLog.Warning(TEXT("Replic: This Blueprint does not currently contain a ReplicTransportComponent. Client-side requests from Self may fail for @@"), this);
		}
	}
}

void UK2Node_ReplicSetEnum::PostReconstructNode()
{
	RefreshValuePinType();
	Super::PostReconstructNode();
}

void UK2Node_ReplicSetEnum::PostLoad()
{
	Super::PostLoad();
	RefreshValuePinType();
}

void UK2Node_ReplicSetEnum::RefreshValuePinType()
{
	if (bIsRefreshingPins)
	{
		return;
	}

	TGuardValue<bool> RefreshGuard(bIsRefreshingPins, true);

	UEdGraphPin* ValuePin = FindPin(ValuePinName);
	UEdGraphPin* PropertyPin = FindPin(PropertyNamePinName);
	if (!ValuePin)
	{
		return;
	}

	FEdGraphPinType NewPinType;
	NewPinType.PinCategory = UEdGraphSchema_K2::PC_Byte;
	if (const UEnum* Enum = ResolveSelectedEnum())
	{
		NewPinType.PinSubCategoryObject = const_cast<UEnum*>(Enum);
		ValuePin->PinType = NewPinType;

		const FName ExistingPinValue = ResolveEnumValueFromPin(ValuePin, Enum);
		if (!bHasPersistedEnumSelection && !ExistingPinValue.IsNone())
		{
			PersistedEnumValue = ExistingPinValue;
			bHasPersistedEnumSelection = true;
		}

		if (ValuePin->LinkedTo.Num() == 0)
		{
			FName EffectiveValue = NAME_None;
			if (!ExistingPinValue.IsNone())
			{
				EffectiveValue = ExistingPinValue;
			}
			else if (bHasPersistedEnumSelection && EnumContainsValueName(Enum, PersistedEnumValue))
			{
				EffectiveValue = PersistedEnumValue;
			}
			else
			{
				EffectiveValue = GetFirstUsableEnumValueName(Enum);
			}

			if (!EffectiveValue.IsNone())
			{
				const FString SerializedValue = EffectiveValue.ToString();
				ValuePin->DefaultValue = SerializedValue;
				ValuePin->AutogeneratedDefaultValue = SerializedValue;
				PersistedEnumValue = EffectiveValue;
				bHasPersistedEnumSelection = true;
			}
		}
	}
	else
	{
		ValuePin->PinType = NewPinType;
		if (ValuePin->LinkedTo.Num() == 0)
		{
			const bool bHasPropertySelection = PropertyPin && !PropertyPin->GetDefaultAsString().IsEmpty();
			if (!bHasPropertySelection)
			{
				bHasPersistedEnumSelection = false;
				PersistedEnumValue = NAME_None;
				ValuePin->DefaultValue.Reset();
				ValuePin->AutogeneratedDefaultValue.Reset();
				ValuePin->DefaultTextValue = FText::GetEmpty();
			}
		}
	}

	ReplicK2NodeUtils::SetPinToolTip(ValuePin, TEXT("New enum value that should be written and replicated."));
	ReplicK2NodeUtils::SetPinToolTip(GetPropertyNamePin(), TEXT("Choose the Replic-marked enum property to write.\n\nThe list is filtered by the connected TargetObject when the editor can resolve it."));
	ReplicK2NodeUtils::SetPinToolTip(GetTargetObjectPin(), TEXT("Object that owns the Replic-marked enum property.\n\nLeave this unconnected only when the property is on Self or in the current Blueprint."));
	ReplicK2NodeUtils::SetPinToolTip(GetContextObjectPin(), TEXT("Object used to identify who is making the network request.\n\nUsually this should be Self on the calling Character, Pawn, PlayerController, Actor, or Component that has access to a ReplicTransportComponent."));
}

const FProperty* UK2Node_ReplicSetEnum::ResolveSelectedEnumProperty() const
{
	const UEdGraphPin* PropertyPin = FindPin(PropertyNamePinName);
	if (!PropertyPin)
	{
		return nullptr;
	}

	const FName SelectedPropertyName(*PropertyPin->GetDefaultAsString());
	const FProperty* Property = nullptr;
	if (ReplicPinOptionResolver::ResolveMarkedProperty(PropertyPin, SelectedPropertyName, Property) && IsEnumLikeProperty(Property))
	{
		return Property;
	}

	return nullptr;
}

UEnum* UK2Node_ReplicSetEnum::ResolveSelectedEnum() const
{
	const UEdGraphPin* PropertyPin = FindPin(PropertyNamePinName);
	if (!PropertyPin)
	{
		return nullptr;
	}

	const FName SelectedPropertyName(*PropertyPin->GetDefaultAsString());
	const FProperty* Property = ResolveSelectedEnumProperty();
	if (Property)
	{
		return ResolveEnumFromProperty(Property);
	}

	return nullptr;
}

FText UK2Node_ReplicSetEnum::GetResolvedDisplayName() const
{
	if (const UEdGraphPin* PropertyPin = FindPin(PropertyNamePinName))
	{
		const FName SelectedPropertyName(*PropertyPin->GetDefaultAsString());
		if (!SelectedPropertyName.IsNone())
		{
			return FText::FromName(SelectedPropertyName);
		}
	}

	return FText::GetEmpty();
}

#undef LOCTEXT_NAMESPACE
