#include "K2Node_ReplicGetArray.h"

#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "EdGraph/EdGraphPin.h"
#include "EdGraphSchema_K2.h"
#include "K2Node_CallFunction.h"
#include "KismetCompiler.h"
#include "ReplicK2NodeUtils.h"
#include "ReplicLibrary.h"
#include "ReplicPinOptionResolver.h"

#define LOCTEXT_NAMESPACE "ReplicGetArrayNode"

namespace
{
	const FName TargetObjectPinName(TEXT("TargetObject"));
	const FName PropertyNamePinName(TEXT("PropertyName"));
	const FName ValuePinName(TEXT("Value"));
	const FName SuccessPinName(TEXT("Success"));

	FEdGraphPinType MakeNeutralArrayPinType()
	{
		FEdGraphPinType PinType;
		PinType.ContainerType = EPinContainerType::Array;
		PinType.PinCategory = UEdGraphSchema_K2::PC_Wildcard;
		return PinType;
	}

	void MovePinLinksOrCopyDefaults(FKismetCompilerContext& CompilerContext, UEdGraphPin* SourcePin, UEdGraphPin* TargetPin)
	{
		if (!SourcePin || !TargetPin)
		{
			return;
		}

		if (SourcePin->LinkedTo.Num() > 0)
		{
			CompilerContext.MovePinLinksToIntermediate(*SourcePin, *TargetPin);
			return;
		}

		TargetPin->DefaultValue = SourcePin->DefaultValue;
		TargetPin->AutogeneratedDefaultValue = SourcePin->AutogeneratedDefaultValue;
		TargetPin->DefaultObject = SourcePin->DefaultObject;
		TargetPin->DefaultTextValue = SourcePin->DefaultTextValue;
	}
}

FName UK2Node_ReplicGetArray::GetTargetObjectPinName() { return TargetObjectPinName; }
FName UK2Node_ReplicGetArray::GetPropertyNamePinName() { return PropertyNamePinName; }
FName UK2Node_ReplicGetArray::GetValuePinName() { return ValuePinName; }
FName UK2Node_ReplicGetArray::GetSuccessPinName() { return SuccessPinName; }

UEdGraphPin* UK2Node_ReplicGetArray::GetTargetObjectPin() const { return FindPinChecked(TargetObjectPinName); }
UEdGraphPin* UK2Node_ReplicGetArray::GetPropertyNamePin() const { return FindPinChecked(PropertyNamePinName); }
UEdGraphPin* UK2Node_ReplicGetArray::GetValuePin() const { return FindPinChecked(ValuePinName); }
UEdGraphPin* UK2Node_ReplicGetArray::GetSuccessPin() const { return FindPinChecked(SuccessPinName); }

void UK2Node_ReplicGetArray::HandleReplicSelectionChanged(FName ChangedPinName)
{
	if (ChangedPinName != PropertyNamePinName || bIsRefreshingPins)
	{
		return;
	}

	ReconstructNode();
	if (UEdGraph* Graph = GetGraph())
	{
		Graph->NotifyNodeChanged(this);
	}
}

void UK2Node_ReplicGetArray::AllocateDefaultPins()
{
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UObject::StaticClass(), TargetObjectPinName);
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Name, PropertyNamePinName);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Wildcard, ValuePinName);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Boolean, SuccessPinName);

	RefreshValuePinType();
	Super::AllocateDefaultPins();
}

void UK2Node_ReplicGetArray::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);

	const FArrayProperty* SelectedProperty = ResolveSelectedArrayProperty();
	if (!SelectedProperty)
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("MissingReplicArrayProperty", "Replic: No valid Replic array property is selected for @@").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	UK2Node_CallFunction* CallNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	CallNode->SetFromFunction(UReplicLibrary::StaticClass()->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UReplicLibrary, GetMarkedArrayInternal)));
	CallNode->AllocateDefaultPins();

	MovePinLinksOrCopyDefaults(CompilerContext, GetTargetObjectPin(), CallNode->FindPinChecked(TargetObjectPinName));
	MovePinLinksOrCopyDefaults(CompilerContext, GetPropertyNamePin(), CallNode->FindPinChecked(PropertyNamePinName));

	UEdGraphPin* IntermediateValuePin = CallNode->FindPinChecked(ValuePinName);
	IntermediateValuePin->PinType = GetValuePin()->PinType;

	CompilerContext.MovePinLinksToIntermediate(*GetValuePin(), *IntermediateValuePin);
	CompilerContext.MovePinLinksToIntermediate(*GetSuccessPin(), *CallNode->GetReturnValuePin());
	BreakAllNodeLinks();
}

void UK2Node_ReplicGetArray::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);
	if (Pin && Pin->PinName == PropertyNamePinName)
	{
		ReconstructNode();
		if (UEdGraph* Graph = GetGraph())
		{
			Graph->NotifyNodeChanged(this);
		}
	}
}

void UK2Node_ReplicGetArray::PinConnectionListChanged(UEdGraphPin* Pin)
{
	Super::PinConnectionListChanged(Pin);
	if (Pin && Pin->PinName == TargetObjectPinName)
	{
		ReconstructNode();
		if (UEdGraph* Graph = GetGraph())
		{
			Graph->NotifyNodeChanged(this);
		}
	}
}

FText UK2Node_ReplicGetArray::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	const FText ResolvedName = GetResolvedDisplayName();
	return ResolvedName.IsEmpty()
		? LOCTEXT("ReplicGetArrayTitle", "Replic Get Array")
		: FText::Format(LOCTEXT("ReplicGetArraySelectedTitle", "Replic Get {0}"), ResolvedName);
}

FText UK2Node_ReplicGetArray::GetTooltipText() const
{
	return LOCTEXT("ReplicGetArrayTooltip", "Reads a Replic-marked array property with a stable typed array pin.\n\nSelect the property first, then this node exposes the matching array type.");
}

FText UK2Node_ReplicGetArray::GetMenuCategory() const
{
	return LOCTEXT("ReplicCategory", "Replic");
}

void UK2Node_ReplicGetArray::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	UClass* ActionKey = GetClass();
	if (!ActionRegistrar.IsOpenForRegistration(ActionKey))
	{
		return;
	}

	UBlueprintNodeSpawner* Spawner = UBlueprintNodeSpawner::Create(GetClass());
	check(Spawner);
	ActionRegistrar.AddBlueprintAction(ActionKey, Spawner);
}

void UK2Node_ReplicGetArray::EarlyValidation(FCompilerResultsLog& MessageLog) const
{
	Super::EarlyValidation(MessageLog);

	const UEdGraphPin* PropertyPin = GetPropertyNamePin();
	const FName SelectedPropertyName(*PropertyPin->GetDefaultAsString());
	if (SelectedPropertyName.IsNone())
	{
		MessageLog.Error(TEXT("Replic: No Replic array property is selected for @@. Choose a marked array in the PropertyName dropdown."), this);
		return;
	}

	const FArrayProperty* SelectedProperty = ResolveSelectedArrayProperty();
	if (!SelectedProperty)
	{
		UClass* TargetClass = nullptr;
		if (!ReplicPinOptionResolver::ResolveTargetClass(PropertyPin, TargetClass))
		{
			MessageLog.Warning(TEXT("Replic: TargetObject could not be resolved to a concrete Blueprint class for @@. Connect a concrete actor/component reference or compile after the TargetObject type is known."), this);
			return;
		}

		MessageLog.Error(
			*FString::Printf(TEXT("Replic: '%s' is not a Replic-marked array property on target class '%s' for @@"), *SelectedPropertyName.ToString(), *TargetClass->GetName()),
			this);
	}
}

void UK2Node_ReplicGetArray::PostReconstructNode()
{
	RefreshValuePinType();
	Super::PostReconstructNode();
}

void UK2Node_ReplicGetArray::PostLoad()
{
	Super::PostLoad();
	RefreshValuePinType();
}

void UK2Node_ReplicGetArray::RefreshValuePinType()
{
	if (bIsRefreshingPins)
	{
		return;
	}

	TGuardValue<bool> RefreshGuard(bIsRefreshingPins, true);

	UEdGraphPin* ValuePin = FindPin(ValuePinName);
	if (!ValuePin)
	{
		return;
	}

	FEdGraphPinType NewPinType = MakeNeutralArrayPinType();
	if (const FArrayProperty* ArrayProperty = ResolveSelectedArrayProperty())
	{
		ReplicK2NodeUtils::ConvertPropertyToPinType(ArrayProperty, NewPinType);
	}

	if (!(ValuePin->PinType == NewPinType))
	{
		ValuePin->PinType = NewPinType;
	}

	ReplicK2NodeUtils::SetPinToolTip(ValuePin, TEXT("Local array value read from the selected Replic property.\n\nThis pin follows the selected array property's type."));
	ReplicK2NodeUtils::SetPinToolTip(GetPropertyNamePin(), TEXT("Choose the Replic-marked array property to read.\n\nThe list is filtered by the connected TargetObject when the editor can resolve it."));
	ReplicK2NodeUtils::SetPinToolTip(GetTargetObjectPin(), TEXT("Object that owns the Replic-marked array property.\n\nLeave this unconnected only when the property is on Self or in the current Blueprint."));
}

const FArrayProperty* UK2Node_ReplicGetArray::ResolveSelectedArrayProperty() const
{
	const UEdGraphPin* PropertyPin = FindPin(PropertyNamePinName);
	if (!PropertyPin)
	{
		return nullptr;
	}

	const FName SelectedPropertyName(*PropertyPin->GetDefaultAsString());
	const FProperty* Property = nullptr;
	if (ReplicPinOptionResolver::ResolveMarkedProperty(PropertyPin, SelectedPropertyName, Property))
	{
		return CastField<FArrayProperty>(Property);
	}

	return nullptr;
}

FText UK2Node_ReplicGetArray::GetResolvedDisplayName() const
{
	if (const UEdGraphPin* PropertyPin = FindPin(PropertyNamePinName))
	{
		const FName SelectedPropertyName(*PropertyPin->GetDefaultAsString());
		if (!SelectedPropertyName.IsNone())
		{
			return FText::FromName(SelectedPropertyName);
		}
	}

	return FText::GetEmpty();
}

#undef LOCTEXT_NAMESPACE
