#include "K2Node_ReplicSetArray.h"

#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "EdGraph/EdGraphPin.h"
#include "EdGraphSchema_K2.h"
#include "K2Node_CallFunction.h"
#include "KismetCompiler.h"
#include "ReplicK2NodeUtils.h"
#include "ReplicLibrary.h"
#include "ReplicPinOptionResolver.h"

#define LOCTEXT_NAMESPACE "ReplicSetArrayNode"

namespace
{
	const FName ExecPinName(TEXT("Execute"));
	const FName ThenPinName(TEXT("Then"));
	const FName ContextObjectPinName(TEXT("ContextObject"));
	const FName TargetObjectPinName(TEXT("TargetObject"));
	const FName PropertyNamePinName(TEXT("PropertyName"));
	const FName ValuePinName(TEXT("Value"));
	const FName SuccessPinName(TEXT("Success"));

	FEdGraphPinType MakeNeutralArrayPinType()
	{
		FEdGraphPinType PinType;
		PinType.ContainerType = EPinContainerType::Array;
		PinType.PinCategory = UEdGraphSchema_K2::PC_Wildcard;
		return PinType;
	}

	void MovePinLinksOrCopyDefaults(FKismetCompilerContext& CompilerContext, UEdGraphPin* SourcePin, UEdGraphPin* TargetPin, bool bPreserveTargetDefaultsWhenSourceUnset = false)
	{
		if (!SourcePin || !TargetPin)
		{
			return;
		}

		if (SourcePin->LinkedTo.Num() > 0)
		{
			CompilerContext.MovePinLinksToIntermediate(*SourcePin, *TargetPin);
			return;
		}

		const bool bSourceHasExplicitDefault =
			!SourcePin->DefaultValue.IsEmpty()
			|| !SourcePin->AutogeneratedDefaultValue.IsEmpty()
			|| SourcePin->DefaultObject != nullptr
			|| !SourcePin->DefaultTextValue.IsEmpty();
		if (!bSourceHasExplicitDefault && bPreserveTargetDefaultsWhenSourceUnset)
		{
			return;
		}

		TargetPin->DefaultValue = SourcePin->DefaultValue;
		TargetPin->AutogeneratedDefaultValue = SourcePin->AutogeneratedDefaultValue;
		TargetPin->DefaultObject = SourcePin->DefaultObject;
		TargetPin->DefaultTextValue = SourcePin->DefaultTextValue;
	}

	bool UsesSelfAsContext(const UEdGraphPin* ContextPin)
	{
		return ContextPin && ContextPin->LinkedTo.Num() == 0 && ContextPin->DefaultObject == nullptr && ContextPin->DefaultValue.IsEmpty();
	}
}

FName UK2Node_ReplicSetArray::GetExecPinName() { return ExecPinName; }
FName UK2Node_ReplicSetArray::GetThenPinName() { return ThenPinName; }
FName UK2Node_ReplicSetArray::GetContextObjectPinName() { return ContextObjectPinName; }
FName UK2Node_ReplicSetArray::GetTargetObjectPinName() { return TargetObjectPinName; }
FName UK2Node_ReplicSetArray::GetPropertyNamePinName() { return PropertyNamePinName; }
FName UK2Node_ReplicSetArray::GetValuePinName() { return ValuePinName; }
FName UK2Node_ReplicSetArray::GetSuccessPinName() { return SuccessPinName; }

UEdGraphPin* UK2Node_ReplicSetArray::GetExecPin() const { return FindPinChecked(ExecPinName); }
UEdGraphPin* UK2Node_ReplicSetArray::GetThenPin() const { return FindPinChecked(ThenPinName); }
UEdGraphPin* UK2Node_ReplicSetArray::GetContextObjectPin() const { return FindPinChecked(ContextObjectPinName); }
UEdGraphPin* UK2Node_ReplicSetArray::GetTargetObjectPin() const { return FindPinChecked(TargetObjectPinName); }
UEdGraphPin* UK2Node_ReplicSetArray::GetPropertyNamePin() const { return FindPinChecked(PropertyNamePinName); }
UEdGraphPin* UK2Node_ReplicSetArray::GetValuePin() const { return FindPinChecked(ValuePinName); }
UEdGraphPin* UK2Node_ReplicSetArray::GetSuccessPin() const { return FindPinChecked(SuccessPinName); }

void UK2Node_ReplicSetArray::HandleReplicSelectionChanged(FName ChangedPinName)
{
	if (ChangedPinName != PropertyNamePinName || bIsRefreshingPins)
	{
		return;
	}

	ReconstructNode();
	if (UEdGraph* Graph = GetGraph())
	{
		Graph->NotifyNodeChanged(this);
	}
}

void UK2Node_ReplicSetArray::AllocateDefaultPins()
{
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Exec, ExecPinName);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, ThenPinName);

	UEdGraphPin* ContextPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UObject::StaticClass(), ContextObjectPinName);
	ContextPin->bAdvancedView = true;
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UObject::StaticClass(), TargetObjectPinName);
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Name, PropertyNamePinName);
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Wildcard, ValuePinName);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Boolean, SuccessPinName);

	RefreshValuePinType();
	Super::AllocateDefaultPins();
}

void UK2Node_ReplicSetArray::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);

	const FArrayProperty* SelectedProperty = ResolveSelectedArrayProperty();
	if (!SelectedProperty)
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("MissingReplicArrayProperty", "Replic: No valid Replic array property is selected for @@").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	UK2Node_CallFunction* CallNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	CallNode->SetFromFunction(UReplicLibrary::StaticClass()->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UReplicLibrary, SetMarkedArrayInternal)));
	CallNode->AllocateDefaultPins();

	CompilerContext.MovePinLinksToIntermediate(*GetExecPin(), *CallNode->GetExecPin());
	CompilerContext.MovePinLinksToIntermediate(*GetThenPin(), *CallNode->GetThenPin());
	MovePinLinksOrCopyDefaults(CompilerContext, GetContextObjectPin(), CallNode->FindPinChecked(ContextObjectPinName), true);
	MovePinLinksOrCopyDefaults(CompilerContext, GetTargetObjectPin(), CallNode->FindPinChecked(TargetObjectPinName));
	MovePinLinksOrCopyDefaults(CompilerContext, GetPropertyNamePin(), CallNode->FindPinChecked(PropertyNamePinName));

	UEdGraphPin* IntermediateValuePin = CallNode->FindPinChecked(ValuePinName);
	IntermediateValuePin->PinType = GetValuePin()->PinType;
	MovePinLinksOrCopyDefaults(CompilerContext, GetValuePin(), IntermediateValuePin);

	CompilerContext.MovePinLinksToIntermediate(*GetSuccessPin(), *CallNode->GetReturnValuePin());
	BreakAllNodeLinks();
}

void UK2Node_ReplicSetArray::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);
	if (Pin && Pin->PinName == PropertyNamePinName)
	{
		ReconstructNode();
		if (UEdGraph* Graph = GetGraph())
		{
			Graph->NotifyNodeChanged(this);
		}
	}
}

void UK2Node_ReplicSetArray::PinConnectionListChanged(UEdGraphPin* Pin)
{
	Super::PinConnectionListChanged(Pin);
	if (Pin && Pin->PinName == TargetObjectPinName)
	{
		ReconstructNode();
		if (UEdGraph* Graph = GetGraph())
		{
			Graph->NotifyNodeChanged(this);
		}
	}
}

FText UK2Node_ReplicSetArray::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	const FText ResolvedName = GetResolvedDisplayName();
	return ResolvedName.IsEmpty()
		? LOCTEXT("ReplicSetArrayTitle", "Replic Set Array")
		: FText::Format(LOCTEXT("ReplicSetArraySelectedTitle", "Replic Set {0}"), ResolvedName);
}

FText UK2Node_ReplicSetArray::GetTooltipText() const
{
	return LOCTEXT("ReplicSetArrayTooltip", "Writes a Replic-marked array property with a stable typed array pin.\n\nSelect the property first, then connect an array of the same type.");
}

FText UK2Node_ReplicSetArray::GetMenuCategory() const
{
	return LOCTEXT("ReplicCategory", "Replic");
}

void UK2Node_ReplicSetArray::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	UClass* ActionKey = GetClass();
	if (!ActionRegistrar.IsOpenForRegistration(ActionKey))
	{
		return;
	}

	UBlueprintNodeSpawner* Spawner = UBlueprintNodeSpawner::Create(GetClass());
	check(Spawner);
	ActionRegistrar.AddBlueprintAction(ActionKey, Spawner);
}

void UK2Node_ReplicSetArray::EarlyValidation(FCompilerResultsLog& MessageLog) const
{
	Super::EarlyValidation(MessageLog);

	const UEdGraphPin* PropertyPin = GetPropertyNamePin();
	const FName SelectedPropertyName(*PropertyPin->GetDefaultAsString());
	if (SelectedPropertyName.IsNone())
	{
		MessageLog.Error(TEXT("Replic: No array property is selected for @@"), this);
		return;
	}

	const FArrayProperty* SelectedProperty = ResolveSelectedArrayProperty();
	if (!SelectedProperty)
	{
		UClass* TargetClass = nullptr;
		if (!ReplicPinOptionResolver::ResolveTargetClass(PropertyPin, TargetClass))
		{
			MessageLog.Warning(TEXT("Replic: TargetObject could not be resolved to a concrete class for @@"), this);
			return;
		}

		MessageLog.Error(
			*FString::Printf(TEXT("Replic: '%s' is not a Replic-marked array property on target class '%s' for @@"), *SelectedPropertyName.ToString(), *TargetClass->GetName()),
			this);
		return;
	}

	if (!ReplicK2NodeUtils::ArePinAndPropertyCompatible(GetValuePin(), SelectedProperty))
	{
		MessageLog.Error(TEXT("Replic: Value pin does not match the selected array property for @@"), this);
	}

	if (const UBlueprint* Blueprint = GetBlueprint())
	{
		if (UsesSelfAsContext(GetContextObjectPin()) && !ReplicK2NodeUtils::HasReplicTransportComponent(Blueprint))
		{
			MessageLog.Warning(TEXT("Replic: This Blueprint does not currently contain a ReplicTransportComponent. Client-side requests from Self may fail for @@"), this);
		}
	}
}

void UK2Node_ReplicSetArray::PostReconstructNode()
{
	RefreshValuePinType();
	Super::PostReconstructNode();
}

void UK2Node_ReplicSetArray::PostLoad()
{
	Super::PostLoad();
	RefreshValuePinType();
}

void UK2Node_ReplicSetArray::RefreshValuePinType()
{
	if (bIsRefreshingPins)
	{
		return;
	}

	TGuardValue<bool> RefreshGuard(bIsRefreshingPins, true);

	UEdGraphPin* ValuePin = FindPin(ValuePinName);
	if (!ValuePin)
	{
		return;
	}

	FEdGraphPinType NewPinType = MakeNeutralArrayPinType();
	if (const FArrayProperty* ArrayProperty = ResolveSelectedArrayProperty())
	{
		ReplicK2NodeUtils::ConvertPropertyToPinType(ArrayProperty, NewPinType);
	}

	const UEdGraphSchema_K2* K2Schema = GetDefault<UEdGraphSchema_K2>();
	if (!(ValuePin->PinType == NewPinType))
	{
		if (K2Schema && !K2Schema->ArePinTypesCompatible(ValuePin->PinType, NewPinType))
		{
			ValuePin->BreakAllPinLinks();
		}

		ValuePin->PinType = NewPinType;
	}

	if (ValuePin->LinkedTo.Num() == 0 && NewPinType.PinCategory == UEdGraphSchema_K2::PC_Wildcard)
	{
		ValuePin->DefaultValue.Reset();
		ValuePin->AutogeneratedDefaultValue.Reset();
		ValuePin->DefaultObject = nullptr;
		ValuePin->DefaultTextValue = FText::GetEmpty();
	}

	ReplicK2NodeUtils::SetPinToolTip(ValuePin, TEXT("New array value written to the selected Replic property.\n\nThis pin must match the selected array property's type."));
	ReplicK2NodeUtils::SetPinToolTip(GetPropertyNamePin(), TEXT("Choose the Replic-marked array property to write.\n\nThe list is filtered by the connected TargetObject when the editor can resolve it."));
	ReplicK2NodeUtils::SetPinToolTip(GetTargetObjectPin(), TEXT("Object that owns the Replic-marked array property.\n\nLeave this unconnected only when the property is on Self or in the current Blueprint."));
	ReplicK2NodeUtils::SetPinToolTip(GetContextObjectPin(), TEXT("Object used to identify who is making the network request.\n\nUsually this should be Self on the calling Character, Pawn, PlayerController, Actor, or Component that has access to a ReplicTransportComponent."));
}

const FArrayProperty* UK2Node_ReplicSetArray::ResolveSelectedArrayProperty() const
{
	const UEdGraphPin* PropertyPin = FindPin(PropertyNamePinName);
	if (!PropertyPin)
	{
		return nullptr;
	}

	const FName SelectedPropertyName(*PropertyPin->GetDefaultAsString());
	const FProperty* Property = nullptr;
	if (ReplicPinOptionResolver::ResolveMarkedProperty(PropertyPin, SelectedPropertyName, Property))
	{
		return CastField<FArrayProperty>(Property);
	}

	return nullptr;
}

FText UK2Node_ReplicSetArray::GetResolvedDisplayName() const
{
	if (const UEdGraphPin* PropertyPin = FindPin(PropertyNamePinName))
	{
		const FName SelectedPropertyName(*PropertyPin->GetDefaultAsString());
		if (!SelectedPropertyName.IsNone())
		{
			return FText::FromName(SelectedPropertyName);
		}
	}

	return FText::GetEmpty();
}

#undef LOCTEXT_NAMESPACE
