#include "K2Node_ReplicGetEnum.h"

#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "EdGraph/EdGraphPin.h"
#include "EdGraphSchema_K2.h"
#include "K2Node_CallFunction.h"
#include "KismetCompiler.h"
#include "ReplicLibrary.h"
#include "ReplicPinOptionResolver.h"

#define LOCTEXT_NAMESPACE "ReplicGetEnumNode"

namespace
{
	const FName TargetObjectPinName(TEXT("TargetObject"));
	const FName PropertyNamePinName(TEXT("PropertyName"));
	const FName ValuePinName(TEXT("Value"));
	const FName SuccessPinName(TEXT("Success"));

	bool IsEnumLikeProperty(const FProperty* Property)
	{
		if (CastField<FEnumProperty>(Property))
		{
			return true;
		}

		if (const FByteProperty* ByteProperty = CastField<FByteProperty>(Property))
		{
			return ByteProperty->Enum != nullptr;
		}

		return false;
	}

	UEnum* ResolveEnumFromProperty(const FProperty* Property)
	{
		if (const FEnumProperty* EnumProperty = CastField<FEnumProperty>(Property))
		{
			return EnumProperty->GetEnum();
		}

		if (const FByteProperty* ByteProperty = CastField<FByteProperty>(Property))
		{
			return ByteProperty->Enum;
		}

		return nullptr;
	}

	void MovePinLinksOrCopyDefaults(FKismetCompilerContext& CompilerContext, UEdGraphPin* SourcePin, UEdGraphPin* TargetPin)
	{
		if (!SourcePin || !TargetPin)
		{
			return;
		}

		if (SourcePin->LinkedTo.Num() > 0)
		{
			CompilerContext.MovePinLinksToIntermediate(*SourcePin, *TargetPin);
			return;
		}

		TargetPin->DefaultValue = SourcePin->DefaultValue;
		TargetPin->AutogeneratedDefaultValue = SourcePin->AutogeneratedDefaultValue;
		TargetPin->DefaultObject = SourcePin->DefaultObject;
		TargetPin->DefaultTextValue = SourcePin->DefaultTextValue;
	}
}

FName UK2Node_ReplicGetEnum::GetTargetObjectPinName() { return TargetObjectPinName; }
FName UK2Node_ReplicGetEnum::GetPropertyNamePinName() { return PropertyNamePinName; }
FName UK2Node_ReplicGetEnum::GetValuePinName() { return ValuePinName; }
FName UK2Node_ReplicGetEnum::GetSuccessPinName() { return SuccessPinName; }

UEdGraphPin* UK2Node_ReplicGetEnum::GetTargetObjectPin() const { return FindPinChecked(TargetObjectPinName); }
UEdGraphPin* UK2Node_ReplicGetEnum::GetPropertyNamePin() const { return FindPinChecked(PropertyNamePinName); }
UEdGraphPin* UK2Node_ReplicGetEnum::GetValuePin() const { return FindPinChecked(ValuePinName); }
UEdGraphPin* UK2Node_ReplicGetEnum::GetSuccessPin() const { return FindPinChecked(SuccessPinName); }

void UK2Node_ReplicGetEnum::HandleReplicSelectionChanged(FName ChangedPinName)
{
	if (ChangedPinName != PropertyNamePinName || bIsRefreshingPins)
	{
		return;
	}

	ReconstructNode();
	if (UEdGraph* Graph = GetGraph())
	{
		Graph->NotifyNodeChanged(this);
	}
}

void UK2Node_ReplicGetEnum::AllocateDefaultPins()
{
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UObject::StaticClass(), TargetObjectPinName);
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Name, PropertyNamePinName);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Byte, ValuePinName);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Boolean, SuccessPinName);

	RefreshValuePinType();
	Super::AllocateDefaultPins();
}

void UK2Node_ReplicGetEnum::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);

	const FProperty* SelectedProperty = ResolveSelectedEnumProperty();
	if (!SelectedProperty)
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("MissingReplicEnumProperty", "Replic: No valid Replic enum property is selected for @@").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	UK2Node_CallFunction* CallNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	CallNode->SetFromFunction(UReplicLibrary::StaticClass()->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UReplicLibrary, GetMarkedEnum)));
	CallNode->AllocateDefaultPins();

	MovePinLinksOrCopyDefaults(CompilerContext, GetTargetObjectPin(), CallNode->FindPinChecked(TargetObjectPinName));
	MovePinLinksOrCopyDefaults(CompilerContext, GetPropertyNamePin(), CallNode->FindPinChecked(PropertyNamePinName));

	UEdGraphPin* IntermediateValuePin = CallNode->FindPinChecked(ValuePinName);
	IntermediateValuePin->PinType = GetValuePin()->PinType;

	CompilerContext.MovePinLinksToIntermediate(*GetValuePin(), *IntermediateValuePin);
	CompilerContext.MovePinLinksToIntermediate(*GetSuccessPin(), *CallNode->GetReturnValuePin());
	BreakAllNodeLinks();
}

void UK2Node_ReplicGetEnum::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);
	if (Pin && Pin->PinName == PropertyNamePinName)
	{
		ReconstructNode();
		if (UEdGraph* Graph = GetGraph())
		{
			Graph->NotifyNodeChanged(this);
		}
	}
}

void UK2Node_ReplicGetEnum::PinConnectionListChanged(UEdGraphPin* Pin)
{
	Super::PinConnectionListChanged(Pin);
	if (Pin && Pin->PinName == TargetObjectPinName)
	{
		ReconstructNode();
		if (UEdGraph* Graph = GetGraph())
		{
			Graph->NotifyNodeChanged(this);
		}
	}
}

FText UK2Node_ReplicGetEnum::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	const FText ResolvedName = GetResolvedDisplayName();
	return ResolvedName.IsEmpty()
		? LOCTEXT("ReplicGetEnumTitle", "Replic Get Enum")
		: FText::Format(LOCTEXT("ReplicGetEnumSelectedTitle", "Replic Get {0}"), ResolvedName);
}

FText UK2Node_ReplicGetEnum::GetTooltipText() const
{
	return LOCTEXT("ReplicGetEnumTooltip", "Reads a Replic-marked enum property with a real enum pin.\n\nSelect the property first, then this node exposes the correct enum type.");
}

FText UK2Node_ReplicGetEnum::GetMenuCategory() const
{
	return LOCTEXT("ReplicCategory", "Replic");
}

void UK2Node_ReplicGetEnum::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	UClass* ActionKey = GetClass();
	if (!ActionRegistrar.IsOpenForRegistration(ActionKey))
	{
		return;
	}

	UBlueprintNodeSpawner* Spawner = UBlueprintNodeSpawner::Create(GetClass());
	check(Spawner);
	ActionRegistrar.AddBlueprintAction(ActionKey, Spawner);
}

void UK2Node_ReplicGetEnum::EarlyValidation(FCompilerResultsLog& MessageLog) const
{
	Super::EarlyValidation(MessageLog);

	const UEdGraphPin* PropertyPin = GetPropertyNamePin();
	const FName SelectedPropertyName(*PropertyPin->GetDefaultAsString());
	if (SelectedPropertyName.IsNone())
	{
		MessageLog.Error(TEXT("Replic: No enum property is selected for @@"), this);
		return;
	}

	const FProperty* SelectedProperty = ResolveSelectedEnumProperty();
	if (!SelectedProperty)
	{
		UClass* TargetClass = nullptr;
		if (!ReplicPinOptionResolver::ResolveTargetClass(PropertyPin, TargetClass))
		{
			MessageLog.Warning(TEXT("Replic: TargetObject could not be resolved to a concrete class for @@"), this);
			return;
		}

		MessageLog.Error(
			*FString::Printf(TEXT("Replic: '%s' is not a Replic-marked enum property on target class '%s' for @@"), *SelectedPropertyName.ToString(), *TargetClass->GetName()),
			this);
		return;
	}
}

void UK2Node_ReplicGetEnum::PostReconstructNode()
{
	RefreshValuePinType();
	Super::PostReconstructNode();
}

void UK2Node_ReplicGetEnum::RefreshValuePinType()
{
	if (bIsRefreshingPins)
	{
		return;
	}

	TGuardValue<bool> RefreshGuard(bIsRefreshingPins, true);

	UEdGraphPin* ValuePin = FindPin(ValuePinName);
	if (!ValuePin)
	{
		return;
	}

	FEdGraphPinType NewPinType;
	NewPinType.PinCategory = UEdGraphSchema_K2::PC_Byte;
	if (const UEnum* Enum = ResolveSelectedEnum())
	{
		NewPinType.PinSubCategoryObject = const_cast<UEnum*>(Enum);
	}

	ValuePin->PinType = NewPinType;
}

const FProperty* UK2Node_ReplicGetEnum::ResolveSelectedEnumProperty() const
{
	const UEdGraphPin* PropertyPin = FindPin(PropertyNamePinName);
	if (!PropertyPin)
	{
		return nullptr;
	}

	const FName SelectedPropertyName(*PropertyPin->GetDefaultAsString());
	const FProperty* Property = nullptr;
	if (ReplicPinOptionResolver::ResolveMarkedProperty(PropertyPin, SelectedPropertyName, Property) && IsEnumLikeProperty(Property))
	{
		return Property;
	}

	return nullptr;
}

UEnum* UK2Node_ReplicGetEnum::ResolveSelectedEnum() const
{
	const UEdGraphPin* PropertyPin = FindPin(PropertyNamePinName);
	if (!PropertyPin)
	{
		return nullptr;
	}

	const FName SelectedPropertyName(*PropertyPin->GetDefaultAsString());
	const FProperty* Property = ResolveSelectedEnumProperty();
	if (Property)
	{
		return ResolveEnumFromProperty(Property);
	}

	return nullptr;
}

FText UK2Node_ReplicGetEnum::GetResolvedDisplayName() const
{
	if (const UEdGraphPin* PropertyPin = FindPin(PropertyNamePinName))
	{
		const FName SelectedPropertyName(*PropertyPin->GetDefaultAsString());
		if (!SelectedPropertyName.IsNone())
		{
			return FText::FromName(SelectedPropertyName);
		}
	}

	return FText::GetEmpty();
}

#undef LOCTEXT_NAMESPACE
