#include "SReplicEnumValuePin.h"

#include "EdGraph/EdGraphPin.h"
#include "EdGraph/EdGraphSchema.h"
#include "K2Node_ReplicSetEnum.h"
#include "Misc\DefaultValueHelper.h"
#include "ScopedTransaction.h"
#include "UObject/UnrealType.h"
#include "Widgets/Input/SComboBox.h"
#include "Widgets/Text/STextBlock.h"

namespace
{
	FName ResolveCurrentEnumValueName(const UEdGraphPin* GraphPin)
	{
		if (!GraphPin)
		{
			return NAME_None;
		}

		const UEnum* Enum = Cast<UEnum>(GraphPin->PinType.PinSubCategoryObject.Get());
		if (!Enum)
		{
			return FName(*GraphPin->GetDefaultAsString());
		}

		FString CurrentValueString = GraphPin->GetDefaultAsString();
		if (CurrentValueString.IsEmpty())
		{
			CurrentValueString = GraphPin->AutogeneratedDefaultValue;
		}

		if (CurrentValueString.IsEmpty())
		{
			if (const UK2Node_ReplicSetEnum* EnumNode = Cast<UK2Node_ReplicSetEnum>(GraphPin->GetOwningNode()))
			{
				return EnumNode->HasPersistedEnumSelection() ? EnumNode->GetPersistedEnumValue() : NAME_None;
			}

			return NAME_None;
		}

		int64 NumericValue = 0;
		if (FDefaultValueHelper::ParseInt64(CurrentValueString, NumericValue))
		{
			const FString NameString = Enum->GetNameStringByValue(NumericValue);
			return NameString.IsEmpty() ? NAME_None : FName(*NameString);
		}

		return FName(*CurrentValueString);
	}
}

void SReplicEnumValuePin::Construct(const FArguments& InArgs, UEdGraphPin* InGraphPinObj)
{
	SGraphPin::Construct(SGraphPin::FArguments(), InGraphPinObj);
	RefreshOptions();
}

TSharedRef<SWidget> SReplicEnumValuePin::GetDefaultValueWidget()
{
	RefreshOptions();

	return SAssignNew(ComboBox, SComboBox<TSharedPtr<FReplicPinOptionItem>>)
		.OptionsSource(&Options)
		.InitiallySelectedItem(GetSelectedItem())
		.OnComboBoxOpening(this, &SReplicEnumValuePin::HandleComboBoxOpening)
		.OnGenerateWidget(this, &SReplicEnumValuePin::GenerateOptionWidget)
		.OnSelectionChanged(this, &SReplicEnumValuePin::HandleSelectionChanged)
		.Visibility(this, &SGraphPin::GetDefaultValueVisibility)
		[
			SNew(STextBlock)
			.Text(this, &SReplicEnumValuePin::GetSelectedItemText)
			.ToolTipText(this, &SReplicEnumValuePin::GetSelectedItemTooltip)
		];
}

void SReplicEnumValuePin::RefreshOptions()
{
	Options.Reset();

	if (!GraphPinObj)
	{
		return;
	}

	UEnum* Enum = Cast<UEnum>(GraphPinObj->PinType.PinSubCategoryObject.Get());
	if (!Enum)
	{
		return;
	}

	const int32 EnumCount = Enum->NumEnums();
	for (int32 Index = 0; Index < EnumCount; ++Index)
	{
		if (Enum->HasMetaData(TEXT("Hidden"), Index))
		{
			continue;
		}

		const FString NameString = Enum->GetNameStringByIndex(Index);
		if (NameString.EndsWith(TEXT("_MAX")))
		{
			continue;
		}

		TSharedPtr<FReplicPinOptionItem> Item = MakeShared<FReplicPinOptionItem>();
		Item->Value = FName(*NameString);
		Item->DisplayText = Enum->GetDisplayNameTextByIndex(Index);
		Item->TooltipText = FText::FromString(FString::Printf(TEXT("Enum value: %s"), *NameString));
		Item->SortKey = FString::Printf(TEXT("%04d_%s"), Index, *NameString);
		Options.Add(Item);
	}
}

void SReplicEnumValuePin::HandleComboBoxOpening()
{
	RefreshOptions();
	if (ComboBox.IsValid())
	{
		ComboBox->RefreshOptions();
		ComboBox->SetSelectedItem(GetSelectedItem());
	}
}

void SReplicEnumValuePin::HandleSelectionChanged(TSharedPtr<FReplicPinOptionItem> SelectedItem, ESelectInfo::Type SelectInfo)
{
	if (!SelectedItem.IsValid())
	{
		return;
	}

	if (const UEdGraphSchema* Schema = GraphPinObj ? GraphPinObj->GetSchema() : nullptr)
	{
		const FString NewValue = SelectedItem->Value.IsNone() ? FString() : SelectedItem->Value.ToString();
		const FName CurrentValueName = ResolveCurrentEnumValueName(GraphPinObj);
		if (!SelectedItem->Value.IsNone() && CurrentValueName != SelectedItem->Value)
		{
			const FScopedTransaction Transaction(NSLOCTEXT("ReplicEditor", "ChangeReplicEnumValuePin", "Change Replic Enum Value"));
			GraphPinObj->Modify();
			Schema->TrySetDefaultValue(*GraphPinObj, NewValue);

			if (UK2Node_ReplicSetEnum* EnumNode = Cast<UK2Node_ReplicSetEnum>(GraphPinObj->GetOwningNode()))
			{
				EnumNode->HandleEnumValueSelectionChanged(SelectedItem->Value);
			}
		}
	}
}

TSharedRef<SWidget> SReplicEnumValuePin::GenerateOptionWidget(TSharedPtr<FReplicPinOptionItem> Item) const
{
	return SNew(STextBlock)
		.Text(Item.IsValid() ? Item->DisplayText : FText::GetEmpty())
		.ToolTipText(Item.IsValid() ? Item->TooltipText : FText::GetEmpty());
}

TSharedPtr<FReplicPinOptionItem> SReplicEnumValuePin::GetSelectedItem() const
{
	if (!GraphPinObj)
	{
		return nullptr;
	}

	const FName CurrentValue = ResolveCurrentEnumValueName(GraphPinObj);
	for (const TSharedPtr<FReplicPinOptionItem>& Item : Options)
	{
		if (Item.IsValid() && Item->Value == CurrentValue)
		{
			return Item;
		}
	}

	if (CurrentValue.IsNone())
	{
		return nullptr;
	}

	TSharedPtr<FReplicPinOptionItem> FallbackItem = MakeShared<FReplicPinOptionItem>();
	FallbackItem->Value = CurrentValue;
	FallbackItem->DisplayText = FText::FromName(CurrentValue);
	FallbackItem->TooltipText = FText::FromString(TEXT("Current enum value is not available in the filtered Replic option list."));
	return FallbackItem;
}

FText SReplicEnumValuePin::GetSelectedItemText() const
{
	if (const TSharedPtr<FReplicPinOptionItem> SelectedItem = GetSelectedItem())
	{
		return SelectedItem->DisplayText;
	}

	return NSLOCTEXT("ReplicEditor", "SelectReplicEnumValue", "Select...");
}

FText SReplicEnumValuePin::GetSelectedItemTooltip() const
{
	if (const TSharedPtr<FReplicPinOptionItem> SelectedItem = GetSelectedItem())
	{
		return SelectedItem->TooltipText;
	}

	return NSLOCTEXT("ReplicEditor", "SelectReplicEnumValueTooltip", "Choose an enum value.");
}
