#include "SReplicMapValuePin.h"

#include "EdGraph/EdGraphPin.h"
#include "EdGraphSchema_K2.h"
#include "K2Node.h"
#include "K2Node_CallFunction.h"
#include "ReplicK2NodeUtils.h"
#include "ReplicLibrary.h"
#include "ReplicPinOptionResolver.h"

namespace
{
	FEdGraphPinType MakeNeutralMapPinType()
	{
		FEdGraphPinType NeutralPinType;
		NeutralPinType.ContainerType = EPinContainerType::Map;
		NeutralPinType.PinCategory = UEdGraphSchema_K2::PC_Wildcard;
		NeutralPinType.PinSubCategory = NAME_None;
		NeutralPinType.PinSubCategoryObject = nullptr;
		NeutralPinType.PinValueType.TerminalCategory = UEdGraphSchema_K2::PC_Wildcard;
		NeutralPinType.PinValueType.TerminalSubCategory = NAME_None;
		NeutralPinType.PinValueType.TerminalSubCategoryObject = nullptr;
		return NeutralPinType;
	}

	bool IsReplicMapValuePin(const UEdGraphPin* Pin)
	{
		if (!Pin || Pin->PinName != TEXT("Value"))
		{
			return false;
		}

		const UK2Node_CallFunction* CallFunctionNode = Cast<UK2Node_CallFunction>(Pin->GetOwningNode());
		const UFunction* TargetFunction = CallFunctionNode ? CallFunctionNode->GetTargetFunction() : nullptr;
		if (!TargetFunction || TargetFunction->GetOwnerClass() != UReplicLibrary::StaticClass())
		{
			return false;
		}

		const FName FunctionName = TargetFunction->GetFName();
		return FunctionName == GET_FUNCTION_NAME_CHECKED(UReplicLibrary, SetMarkedMap)
			|| FunctionName == GET_FUNCTION_NAME_CHECKED(UReplicLibrary, GetMarkedMap);
	}

	bool TryResolveSelectedMapPropertyPinType(const UEdGraphPin* ValuePin, FEdGraphPinType& OutPinType)
	{
		if (!IsReplicMapValuePin(ValuePin))
		{
			return false;
		}

		const UK2Node_CallFunction* CallFunctionNode = Cast<UK2Node_CallFunction>(ValuePin->GetOwningNode());
		const UEdGraphPin* PropertyNamePin = CallFunctionNode ? CallFunctionNode->FindPin(TEXT("PropertyName")) : nullptr;
		if (!PropertyNamePin)
		{
			return false;
		}

		const FName SelectedPropertyName(*PropertyNamePin->GetDefaultAsString());
		if (SelectedPropertyName.IsNone())
		{
			return false;
		}

		const FProperty* Property = nullptr;
		if (!ReplicPinOptionResolver::ResolveMarkedProperty(PropertyNamePin, SelectedPropertyName, Property) || !CastField<FMapProperty>(Property))
		{
			return false;
		}

		return ReplicK2NodeUtils::ConvertPropertyToPinType(Property, OutPinType);
	}
}

void SReplicMapValuePin::Construct(const FArguments& InArgs, UEdGraphPin* InGraphPinObj)
{
	SGraphPin::Construct(SGraphPin::FArguments(), InGraphPinObj);
	SynchronizeMapPinType();
}

void SReplicMapValuePin::Tick(const FGeometry& AllottedGeometry, const double InCurrentTime, const float InDeltaTime)
{
	SynchronizeMapPinType();
	SGraphPin::Tick(AllottedGeometry, InCurrentTime, InDeltaTime);
}

void SReplicMapValuePin::SynchronizeMapPinType() const
{
	if (!GraphPinObj)
	{
		return;
	}

	FEdGraphPinType DesiredPinType;
	if (!TryResolveSelectedMapPropertyPinType(GraphPinObj, DesiredPinType))
	{
		DesiredPinType = MakeNeutralMapPinType();
	}

	if (GraphPinObj->PinType == DesiredPinType)
	{
		return;
	}

	const UEdGraphSchema_K2* K2Schema = GetDefault<UEdGraphSchema_K2>();
	if (K2Schema && !K2Schema->ArePinTypesCompatible(GraphPinObj->PinType, DesiredPinType))
	{
		GraphPinObj->BreakAllPinLinks();
	}

	GraphPinObj->PinType = DesiredPinType;

	if (GraphPinObj->Direction == EGPD_Input && GraphPinObj->LinkedTo.Num() == 0 && DesiredPinType.PinCategory == UEdGraphSchema_K2::PC_Wildcard)
	{
		GraphPinObj->DefaultValue.Reset();
		GraphPinObj->AutogeneratedDefaultValue.Reset();
		GraphPinObj->DefaultObject = nullptr;
		GraphPinObj->DefaultTextValue = FText::GetEmpty();
	}

	if (UEdGraphNode* OwningNode = GraphPinObj->GetOwningNodeUnchecked())
	{
		for (UEdGraphPin* LinkedPin : GraphPinObj->LinkedTo)
		{
			if (LinkedPin)
			{
				if (UK2Node* LinkedK2Node = Cast<UK2Node>(LinkedPin->GetOwningNodeUnchecked()))
				{
					LinkedK2Node->NotifyPinConnectionListChanged(LinkedPin);
				}
			}
		}

		if (UEdGraph* Graph = OwningNode->GetGraph())
		{
			Graph->NotifyNodeChanged(OwningNode);
		}
	}
}
